import {
  Bot,
  Building2,
  Camera,
  Cctv,
  ChartColumn,
  Code,
  Database,
  Drill,
  Droplets,
  Funnel,
  LayoutGrid,
  Megaphone,
  MessageCircle,
  MousePointerClick,
  PenTool,
  Plane,
  Rocket,
  Search,
  Store,
  Users,
  type LucideIcon,
} from "lucide-react";

/** Shared by server and client components, so it lives outside any "use client" module. */
export const serviceIcons: Record<string, LucideIcon> = {
  "digital-marketing": Megaphone,
  "logo-design": PenTool,
  "web-development": Code,
  seo: Search,
  sem: MousePointerClick,
  "social-media-management": Users,
  "instagram-marketing": Camera,
  "lead-generation": Funnel,
  "saas-products": LayoutGrid,
  "ai-automation": Bot,
  "whatsapp-business-solutions": MessageCircle,
  "data-solutions": ChartColumn,
  "digital-data-products": Database,
  "business-marketplace": Store,
  "water-pumps": Droplets,
  "borewell-services": Drill,
  "cctv-security": Cctv,
  travels: Plane,
  "interiors-architecture": Building2,
  "startup-consulting": Rocket,
};
